---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootog
  labels:
    app: bootog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootog
  template:
    metadata:
      labels:
        app: bootog
    spec:
      containers:
        - name: bootog
          image: docker.io/phengbunath/bootog:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
